name: Deploy MkDocs

on:
  release:
    types: [ published ]

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set timezone to UTC
      run: echo "TZ=UTC" >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with=docs --no-interaction --no-ansi

    - name: Deploy docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "ci-bot"
        git config --global user.email "ci-bot@puepy.dev"
        poetry run mike set-default stable
        poetry run mike deploy --push -u stable ${{ github.event.release.name }} --allow-empty
